version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=rootroot
      - DB_NAME=college
      - DB_PORT=5432

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rootroot
      - POSTGRES_DB=college
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 